activation_idx:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
basis_func: gaussian
batch_size: 20000
cs: 5.0
delta:
- 15.0
- 10.0
- 100.0
- 100.0
- 100.0
- 10.0
- 10.0
- 10.0
dimension_ranges:
- - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
epochs: 10000
in_features: 8
lower_bounds:
- - -0.2
- - -0.3
- - 1.0
- - -1.0
- - 3.0
- - -3.4
- - -3.4
- - -0.1
lr: 0.001
mu: 1.0
num_kernels: 50
num_regions: 500
out_features: 10
seed: 123
upper_bounds:
- - 3.0
- - 0.3
- - 7.0
- - 1.0
- - 7.0
- - 3.4
- - 3.4
- - 0.1
