activation_idx:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
basis_func: inverse_quadratic
batch_size: 80000
delta:
- 10.0
- 10.0
- 10.0
- 100.0
- 10.0
- 100.0
- 100.0
dimension_ranges:
- - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
- - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
- - 0
  - 0
  - 0
  - 1
  - 0
  - 0
  - 0
- - 0
  - 0
  - 0
  - 1
  - 0
  - 0
  - 1
- - 0
  - 0
  - 0
  - 1
  - 0
  - 1
  - 0
- - 0
  - 0
  - 0
  - 1
  - 0
  - 1
  - 1
- - 0
  - 0
  - 1
  - 0
  - 0
  - 0
  - 0
- - 0
  - 0
  - 1
  - 0
  - 0
  - 0
  - 1
- - 0
  - 0
  - 1
  - 0
  - 0
  - 1
  - 0
- - 0
  - 0
  - 1
  - 0
  - 0
  - 1
  - 1
- - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 0
- - 0
  - 0
  - 1
  - 1
  - 0
  - 0
  - 1
- - 0
  - 0
  - 1
  - 1
  - 0
  - 1
  - 0
- - 0
  - 0
  - 1
  - 1
  - 0
  - 1
  - 1
epochs: 1000
in_features: 5
lower_bounds:
- - 0.0
- - 0.0
- - -3.6
  - -0.0
- - -3.200000000000006
  - -2.6645352591003757e-15
- - 0.0
- - -0.6
  - -0.19999999999999996
- - 0.0
  - 1.0
lr: 0.001
num_kernels: 10
num_regions: 16
out_features: 10
seed: 123
upper_bounds:
- - 7.0
- - 3.6
- - -0.0
  - 3.6
- - -2.6645352591003757e-15
  - 3.200000000000006
- - 7.0
- - -0.19999999999999996
  - 0.4
- - 1.0
  - 2.5
