activation_idx:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
basis_func: gaussian
batch_size: 20000
cs: 5.0
delta:
- 15.0
- 10.0
- 100.0
- 100.0
- 100.0
- 10.0
- 10.0
- 10.0
dimension_ranges:
- - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 2
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 0
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - 1
  - 2
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - 2
  - 0
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - 2
  - 1
  - 0
- - 0
  - 0
  - 0
  - 0
  - 0
  - 2
  - 2
  - 0
- - 0
  - 0
  - 0
  - 1
  - 0
  - 0
  - 0
  - 0
- - 0
  - 0
  - 0
  - 1
  - 0
  - 0
  - 1
  - 0
- - 0
  - 0
  - 0
  - 1
  - 0
  - 0
  - 2
  - 0
- - 0
  - 0
  - 0
  - 1
  - 0
  - 1
  - 0
  - 0
- - 0
  - 0
  - 0
  - 1
  - 0
  - 1
  - 1
  - 0
- - 0
  - 0
  - 0
  - 1
  - 0
  - 1
  - 2
  - 0
- - 0
  - 0
  - 0
  - 1
  - 0
  - 2
  - 0
  - 0
- - 0
  - 0
  - 0
  - 1
  - 0
  - 2
  - 1
  - 0
- - 0
  - 0
  - 0
  - 1
  - 0
  - 2
  - 2
  - 0
- - 0
  - 0
  - 0
  - 2
  - 0
  - 0
  - 0
  - 0
- - 0
  - 0
  - 0
  - 2
  - 0
  - 0
  - 1
  - 0
- - 0
  - 0
  - 0
  - 2
  - 0
  - 0
  - 2
  - 0
- - 0
  - 0
  - 0
  - 2
  - 0
  - 1
  - 0
  - 0
- - 0
  - 0
  - 0
  - 2
  - 0
  - 1
  - 1
  - 0
- - 0
  - 0
  - 0
  - 2
  - 0
  - 1
  - 2
  - 0
- - 0
  - 0
  - 0
  - 2
  - 0
  - 2
  - 0
  - 0
- - 0
  - 0
  - 0
  - 2
  - 0
  - 2
  - 1
  - 0
- - 0
  - 0
  - 0
  - 2
  - 0
  - 2
  - 2
  - 0
epochs: 10000
in_features: 8
lower_bounds:
- - -0.2
- - -0.3
- - 1.0
- - -1.0
  - -0.3999999999999999
  - 0.20000000000000018
- - 3.0
- - -2.6
  - -1.04
  - 0.52
- - -1.0
  - -0.3999999999999999
  - 0.20000000000000018
- - -0.1
lr: 0.001
mu: 1.0
num_kernels: 500
num_regions: 27
out_features: 10
seed: 123
upper_bounds:
- - 2.0
- - 0.3
- - 7.0
- - -0.3999999999999999
  - 0.20000000000000018
  - 1.0
- - 7.0
- - -1.04
  - 0.52
  - 2.6
- - -0.3999999999999999
  - 0.20000000000000018
  - 1.0
- - 0.1
