activation_idx:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
basis_func: gaussian
batch_size: 80000
cs: 5.0
delta:
- 100.0
- 100.0
- 100.0
- 100.0
- 100.0
- 100.0
- 100.0
dimension_ranges:
- - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
- - 0
  - 0
  - 0
  - 0
  - 1
  - 0
  - 0
- - 0
  - 0
  - 0
  - 0
  - 2
  - 0
  - 0
- - 1
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
- - 1
  - 0
  - 0
  - 0
  - 1
  - 0
  - 0
- - 1
  - 0
  - 0
  - 0
  - 2
  - 0
  - 0
- - 2
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
- - 2
  - 0
  - 0
  - 0
  - 1
  - 0
  - 0
- - 2
  - 0
  - 0
  - 0
  - 2
  - 0
  - 0
epochs: 10000
in_features: 7
lower_bounds:
- - 0.0
  - 2.0
  - 4.0
- - 0.0
- - -1.0
- - -3.4
- - 0.0
  - 2.0
  - 4.0
- - -0.6
- - -3.0
lr: 0.001
mu: 1.0
num_kernels: 100
num_regions: 9
out_features: 2
seed: 123
upper_bounds:
- - 2.0
  - 4.0
  - 8.0
- - 3.6
- - 3.5999999999999988
- - 3.399999999999999
- - 2.0
  - 4.0
  - 8.0
- - 0.4
- - 2.5
