activation_idx:
- 0
- 1
- 2
- 3
- 4
basis_func: inverse_quadratic
batch_size: 2000000
delta:
- 15.0
- 15.0
- 15.0
- 100.0
- 15.0
dimension_ranges:
- - 0
  - 0
  - 0
  - 0
  - 0
- - 0
  - 0
  - 0
  - 1
  - 0
- - 0
  - 0
  - 1
  - 0
  - 0
- - 0
  - 0
  - 1
  - 1
  - 0
- - 0
  - 1
  - 0
  - 0
  - 0
- - 0
  - 1
  - 0
  - 1
  - 0
- - 0
  - 1
  - 1
  - 0
  - 0
- - 0
  - 1
  - 1
  - 1
  - 0
epochs: 1000
in_features: 5
lower_bounds:
- - -1.0
- - -1.2
  - 1.45
- - -4.1
  - 0.0
- - -3.3
  - 0.0
- - -1.0
lr: 0.001
num_kernels: 10
num_regions: 8
out_features: 2
seed: 0
upper_bounds:
- - 8.4
- - 1.45
  - 4.1
- - 0.0
  - 4.1
- - 0.0
  - 3.3
- - 8.4
