activation_idx:
- 0
- 1
- 2
- 3
- 4
basis_func: inverse_quadratic
batch_size: 20000
delta:
- 10.0
- 15.0
- 15.0
- 100.0
- 10.0
dimension_ranges:
- - 0
  - 0
  - 0
  - 0
  - 0
epochs: 1000
in_features: 5
lower_bounds:
- - 0.0
- - 0.0
- - -3.6
- - -3.2
- - 0.0
lr: 0.001
num_kernels: 100
num_regions: 1
out_features: 10
seed: 0
upper_bounds:
- - 7.3
- - 3.6
- - 3.6
- - 3.2
- - 7.3
