activation_idx:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
basis_func: inverse_quadratic
batch_size: 120000
delta:
- 15.0
- 100.0
- 15.0
- 15.0
- 15.0
- 100.0
- 15.0
dimension_ranges:
- - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
epochs: 500
in_features: 7
lower_bounds:
- - -0.401
- - -1.01
- - 0.1
- - 0.01
- - -4.3
- - -2.1
- - 0.1
lr: 0.001
num_kernels: 10
num_regions: 1
out_features: 2
seed: 0
upper_bounds:
- - 0.401
- - 1.01
- - 10.2
- - 4.61
- - 4.3
- - 2.1
- - 10.2
