activation_idx:
- 0
- 1
basis_func: inverse_quadratic
batch_size: 20000
delta:
- 15.0
- 15.0
dimension_ranges:
- - 0
  - 0
epochs: 1000
in_features: 2
lower_bounds:
- - -15.0
- - -15.0
lr: 0.001
num_kernels: 10
num_regions: 1
out_features: 1
seed: 0
upper_bounds:
- - 15.0
- - 15.0
